### ISSUE TITLE
Combining assets

### ISSUE THREAD

**Issue by stefanschleich** [fritzmg/contao-swiper#1]
It would be great if there was an option to add the CSS- and JS-assets to the Combiner with `|static` instead of including them one by one here:

https://github.com/fritzmg/contao-swiper/blob/cc36800a17b4afdeeed5d2a0455e009be756b2c6/src/Elements/WrapperStart.php#L107-L110

**Comment by fritzmg** [comment]
Imho it's better not to do that - unless you have a slider on a majority of your pages. But it could be optional. Or I could integrate it into the stop template.

**Comment by fritzmg** [comment]
Implemented in `3.0.0`.
