### ISSUE TITLE
Start / Stop on mouseover / mouseout

### ISSUE THREAD

**Issue by herrrilke** [fritzmg/contao-swiper#12]
Hallo,
leider schaffe ich es nicht, den slider anzusprechen, um bei mouseover einen stop() zu erwirken:

$('.swiper-slide').on('mouseover', function(){
	swiper.autoplay.stop();
});
	
$('.swiper-slide').on('mouseout', function() {
	  swiper.autoplay.start();
});

swiper wird nicht als objekt erkannt.
wass muss ich nutzen, damit's funktioniert, kannst du das sage?

danke für die feine erweiterung

karsten

**Comment by fritzmg** [comment]
`initSwiper` im `ce_swiperStop` template gibt eine `Swiper` Instanz zurück.

**Comment by herrrilke** [comment]
perfekt! 
danke schön!

hier zum nachlesen der erweiterte code aus dem template:

`<script>
    var ke = initSwiper({
      id: '<?= $this->sliderId ?>',
      wrapperClass: '<?= $this->wrapperClass ?>',
      params: <?= json_encode($this->parameters) ?>
    });

  $('.swiper-slide').on('mouseover', function(){
	ke.autoplay.stop();
   });
		
  $('.swiper-slide').on('mouseout', function() {
	  ke.autoplay.start();
  });
 
  </script>`
