### ISSUE TITLE
Problem mit Safari 14.1 unter Big Sur 11.3.1

### ISSUE THREAD

**Issue by deralteherr** [fritzmg/contao-swiper#18]
Guten Tag,
unter Safari 14.1 unter Big Sur gibt es beim Swiper folgendes Problem:
Bei dem Effekt »Cube« werden die Steuerschaltflächen nicht über den Bildern angezeigt. Über den nicht sichtbaren Schaltflächen wird zwar der Cursor zur Hand und man kann sie auch anklicken, auch die Animation läuft an.
Während des Drehens werden die Steuerschaltflächen sichtbar, verschwinden dann aber sobald das Bild vollständig gedreht ist.
Weder Firefox, noch Vivaldi, Opera oder MS Edge zeigen dieses Verhalten. Bei diesen Browsern sich die Schaltflächen immer über den Bildern zu sehen. Nur Safari macht diesen Ärger.
Grüße

**Comment by fritzmg** [comment]
I don't think there is anything I can do about it, since this extension simply integrates Swiper.js into Contao. What I can do is update Swiper.js to the newest version, may be this problem will not occur then (if that transition effect is still available in the newest version).

**Comment by fritzmg** [comment]
Swiper.js updated to `6.8.4` in version `4.0.0` of this extension. Closing for now.
