### ISSUE TITLE
"Abstand zwischen den Slides" auch negative Werte zulassen

### ISSUE THREAD

**Issue by V15** [fritzmg/contao-swiper#20]
Ich setze gerade eine Galerie mit überlappenden Bildern um.
Dafür wollte ich das Feld "Abstand zwischen den Slides" verwendet.

In dem Feld können aber nur positive Zahlen wie z.B. "50" angegeben werden.
Die Zahl "-50" wird nicht akzeptiert.

Ich kann aber im Feld "Eigene Optionen" problemlos auch eine negative Zahl angeben:
`{"spaceBetween": -50}`

Kannst du die Möglichkeit auch für das Feld "Abstand zwischen den Slides" einrichten?
Danke!

**Comment by fritzmg** [comment]
Try the following customisation:

```php
// contao/dca/tl_content.php
$GLOBALS['TL_DCA']['tl_content']['fields']['sliderSpaceBetween']['eval']['rgxp'] = 'digit';
```

**Comment by fritzmg** [comment]
Also available in `4.0.1` now.
