### ISSUE TITLE
Double Lightbox Items when using hyperlinks/images with lightbox as slider items

### ISSUE THREAD

**Issue by johannes-bittner** [fritzmg/contao-swiper#27]
Tested with Contao 4.13.x, when using either hyperlinks (with YT videos in lightbox) or images with checked lightbox option (e.g. lightbox[90% 100%]), the opened lightbox element gets duplicated, so when clicking next/previous in the lightbox, you see the active image/content twice. Also tested with different lightboxes. Any idea?

**Comment by fritzmg** [comment]
Which Lightbox JavaScript are you using?

**Comment by johannes-bittner** [comment]
Tried with standard Contao j_colorbox, j_lightcase and js_glightbox, same result ...

**Comment by fritzmg** [comment]
> the opened lightbox element gets duplicated, so when clicking next/previous in the lightbox, you see the active image/content twice

You are probably using the **Loop** option. Swiper will then insert duplicates - which means the same duplicates will also be present in the lightbox (if the lightbox is initialized after the Swiper, which is likely always the case).

**Comment by johannes-bittner** [comment]
Loop is active, correct. But even when deactivated, problem persists - 4 slides, 8 images in the lightbox (tried glightbox/colorbox) ...

**Comment by fritzmg** [comment]
Please post a URL where one can see the issue.

**Comment by johannes-bittner** [comment]
https://test.pxls.ch/slider - 3 hyperlink element, 3 images ... interestingly, it works with the images now, but not with the hyperlinks

**Comment by fritzmg** [comment]
Everything works as expected. For each image you have two lightbox-enabled links for the same lightbox group. For example:

```html
<a href="files/system/fenix/img/bg-mountains.jpg" class="hyperlink_img" data-lightbox="lightbox[90% 100%]">…</a>
<a href="files/system/fenix/img/bg-mountains.jpg" class="hyperlink_txt" title="" data-lightbox="lightbox[90% 100%]">…</a>
```

That's why the lightbox shows you the same image twice.

In any case this has nothing to do with this extension at all and you should ask on the Contao Community forum or the Contao Slack for further help, if you need any.

**Comment by johannes-bittner** [comment]
Awesome, thank you for the quick solution/explanation. 
... 🙈 ... read the source, Luke
