### ISSUE TITLE
Lacking compatibility with Conto 5.0.1 i.e. Symphony 6

### ISSUE THREAD

**Issue by Seefahrer** [fritzmg/contao-swiper#28]
The installation of the swiper-extension throws fllwg error message in CM when it is trying to install its dependency
"https://github.com/m-vo/contao-group-widget":

`The service "Mvo\ContaoGroupWidget\Group\Registry" has a dependency on a non-existent service "Psr\Container\ContainerInterface".`

The specified service-alias had been removed in Symphony 6.

**Comment by fritzmg** [comment]
That's not an error of this extension. You would need to report that here https://github.com/m-vo/contao-group-widget

**Comment by Seefahrer** [comment]
Was reported already yesterday in: https://github.com/m-vo/contao-group-widget/issues/45
