### ISSUE TITLE
Autoplay funktioniert nicht

### ISSUE THREAD

**Issue by toblr** [fritzmg/contao-swiper#8]
Der Autoplay-Parameter müsste als "Object" angegeben werden, da sonst die Autoplay-Funktion nicht funktioniert.

`if ($objContent->sliderDelay) $arrParams['autoplay'] = ['delay' => (int)$objContent->sliderDelay];`

[WrapperStop.php in Zeile 88](https://github.com/fritzmg/contao-swiper/blob/master/src/Elements/WrapperStop.php#L88)

**Comment by fritzmg** [comment]
Hm.. kann ich nicht nachvollziehen, autoplay funktioniert. Zu mal sollte es keinen Unterschied machen, ob man
```php
$arrParams['autoplay']['delay'] = (int)$objContent->sliderDelay;
```
oder
```php
$arrParams['autoplay'] = ['delay' => (int)$objContent->sliderDelay];
```
schreibt.

Ich gebe dir aber recht, dass letztzeres die "bessere" Schreibweise ist, da das associative Array an dieser Stelle ja so noch nicht existiert :)
